services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.prod
    container_name: sanchez_carrion_backend_prod
    env_file:
      - ./backend/.env.prod
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/admin/"]
      interval: 30s
      timeout: 10s
      retries: 3

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
    container_name: sanchez_carrion_frontend_prod
    ports:
      - "81:80"
    depends_on:
      - backend
    restart: unless-stopped

  db:
    image: postgres:17.9-alpine
    container_name: sanchez_carrion_db_prod
    env_file:
      - ./backend/.env.prod
    ports:
      - "5433:5432"
    volumes:
      - sanchez_carrion_postgres_data_prod:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  sanchez_carrion_postgres_data_prod: