# Generated by Django 6.0.3 on 2026-06-22 13:08

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('es_para_lf', models.BooleanField(default=True)),
                ('es_para_itse', models.BooleanField(default=True)),
                ('esta_activo', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'estados',
            },
        ),
        migrations.CreateModel(
            name='NivelRiesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('esta_activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'niveles_riesgo',
            },
        ),
        migrations.CreateModel(
            name='TipoDocumentoIdentidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('esta_activo', models.BooleanField(default=True)),
                ('es_para_natural', models.BooleanField(default=True)),
                ('es_para_juridica', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tipos_documento_identidad',
            },
        ),
        migrations.CreateModel(
            name='TipoLetrero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('esta_activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tipos_letrero',
            },
        ),
        migrations.CreateModel(
            name='TipoLicencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('esta_activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'tipos_licencia',
            },
        ),
        migrations.CreateModel(
            name='UnidadOrganica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('sigla', models.CharField(max_length=50)),
                ('esta_activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'unidades_organicas',
            },
        ),
        migrations.CreateModel(
            name='Expediente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('numero_expediente', models.PositiveIntegerField()),
                ('fecha_recepcion', models.DateTimeField()),
                ('observaciones', models.CharField(blank=True, max_length=250, null=True)),
                ('fecha_vencimiento', models.DateField()),
                ('fecha_alerta', models.DateField()),
                ('fecha_suspension', models.DateField(blank=True, null=True)),
                ('dias_ampliacion', models.PositiveIntegerField(blank=True, null=True)),
                ('motivo_ampliacion', models.CharField(blank=True, max_length=250, null=True)),
                ('fecha_digitacion_ampliacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_digitacion', models.DateTimeField()),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.PROTECT, related_name='expedientes_digitados', to=settings.AUTH_USER_MODEL)),
                ('usuario_ampliacion', models.ForeignKey(blank=True, db_column='usuario_ampliacion', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expedientes_ampliacion_digitadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'expedientes',
            },
        ),
        migrations.CreateModel(
            name='ExpedienteArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('nombre_original', models.CharField(max_length=255)),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('ruta_archivo', models.CharField(max_length=500)),
                ('extension', models.CharField(max_length=20)),
                ('tamanio_bytes', models.BigIntegerField()),
                ('fecha_digitacion', models.DateTimeField()),
                ('expediente', models.ForeignKey(db_column='expediente_id', on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='app_lf_itse.expediente')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'expedientes_archivos',
            },
        ),
        migrations.CreateModel(
            name='FeriadoAnual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feriado', models.DateField(unique=True)),
                ('fecha_digitacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'feriados_anuales',
                'ordering': ['feriado'],
            },
        ),
        migrations.CreateModel(
            name='FeriadoRecurrente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('mes', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
            ],
            options={
                'db_table': 'feriados_recurrentes',
                'ordering': ['mes', 'dia'],
                'constraints': [models.UniqueConstraint(fields=('dia', 'mes'), name='uq_feriados_rec_dia_mes')],
            },
        ),
        migrations.CreateModel(
            name='Giro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciiu_id', models.PositiveIntegerField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=200)),
                ('esta_activo', models.BooleanField(default=True)),
                ('fecha_digitacion', models.DateTimeField()),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'giros',
            },
        ),
        migrations.CreateModel(
            name='Inspector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido_paterno', models.CharField(max_length=50)),
                ('apellido_materno', models.CharField(max_length=50)),
                ('nombres', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, null=True)),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.PROTECT, related_name='inspectores_digitados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inspectores',
            },
        ),
        migrations.CreateModel(
            name='Itse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('tipo_itse_id', models.PositiveIntegerField()),
                ('numero_itse', models.PositiveIntegerField(unique=True)),
                ('fecha_expedicion', models.DateField()),
                ('fecha_solicitud_renovacion', models.DateField()),
                ('fecha_caducidad', models.DateField()),
                ('nombre_comercial', models.CharField(max_length=250)),
                ('direccion', models.CharField(max_length=250)),
                ('resolucion_numero', models.CharField(max_length=50)),
                ('area', models.DecimalField(decimal_places=2, max_digits=18)),
                ('numero_recibo_pago', models.CharField(max_length=20)),
                ('observaciones', models.TextField()),
                ('se_puede_publicar', models.BooleanField(default=False)),
                ('capacidad_aforo', models.PositiveIntegerField()),
                ('fecha_notificacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_digitacion', models.DateTimeField()),
                ('expediente', models.ForeignKey(db_column='expediente_id', on_delete=django.db.models.deletion.PROTECT, related_name='itse', to='app_lf_itse.expediente')),
                ('itse_principal', models.ForeignKey(blank=True, db_column='itse_principal_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='itse_dependientes', to='app_lf_itse.itse')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.PROTECT, related_name='itse_digitados', to=settings.AUTH_USER_MODEL)),
                ('nivel_riesgo', models.ForeignKey(db_column='nivel_riesgo_id', on_delete=django.db.models.deletion.PROTECT, to='app_lf_itse.nivelriesgo')),
            ],
            options={
                'db_table': 'itse',
            },
        ),
        migrations.CreateModel(
            name='ItseArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('nombre_original', models.CharField(max_length=255)),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('ruta_archivo', models.CharField(max_length=500)),
                ('extension', models.CharField(max_length=20)),
                ('tamanio_bytes', models.BigIntegerField()),
                ('fecha_digitacion', models.DateTimeField()),
                ('itse', models.ForeignKey(db_column='itse_id', on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='app_lf_itse.itse')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'itse_archivos',
            },
        ),
        migrations.CreateModel(
            name='ItseEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_estado', models.DateField()),
                ('documento', models.CharField(max_length=100)),
                ('observaciones', models.CharField(max_length=1000)),
                ('fecha_digitacion', models.DateTimeField()),
                ('estado', models.ForeignKey(db_column='estado_id', on_delete=django.db.models.deletion.PROTECT, to='app_lf_itse.estado')),
                ('itse', models.ForeignKey(db_column='itse_id', on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='app_lf_itse.itse')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'itse_estados',
            },
        ),
        migrations.CreateModel(
            name='ItseGiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_digitacion', models.DateTimeField()),
                ('giro', models.ForeignKey(db_column='giro_id', on_delete=django.db.models.deletion.PROTECT, to='app_lf_itse.giro')),
                ('itse', models.ForeignKey(db_column='itse_id', on_delete=django.db.models.deletion.CASCADE, related_name='giros', to='app_lf_itse.itse')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'itse_giros',
            },
        ),
        migrations.CreateModel(
            name='ItseInspector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, null=True)),
                ('inspector', models.ForeignKey(db_column='inspector_id', on_delete=django.db.models.deletion.PROTECT, related_name='itse_asignadas', to='app_lf_itse.inspector')),
                ('itse', models.ForeignKey(db_column='itse_id', on_delete=django.db.models.deletion.CASCADE, related_name='inspectores', to='app_lf_itse.itse')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.PROTECT, related_name='itse_inspectores_digitados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'itse_inspectores',
            },
        ),
        migrations.CreateModel(
            name='LicenciaFuncionamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('numero_licencia', models.PositiveIntegerField(unique=True)),
                ('fecha_emision', models.DateField()),
                ('nombre_comercial', models.CharField(max_length=250)),
                ('es_vigencia_indeterminada', models.BooleanField(default=True)),
                ('fecha_inicio_vigencia', models.DateField(blank=True, null=True)),
                ('fecha_fin_vigencia', models.DateField(blank=True, null=True)),
                ('actividad', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=250)),
                ('hora_desde', models.IntegerField()),
                ('hora_hasta', models.IntegerField()),
                ('resolucion_numero', models.CharField(max_length=50)),
                ('area', models.DecimalField(decimal_places=2, max_digits=18)),
                ('numero_recibo_pago', models.CharField(max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('se_puede_publicar', models.BooleanField(default=False)),
                ('fecha_notificacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_digitacion', models.DateTimeField()),
                ('expediente', models.ForeignKey(db_column='expediente_id', on_delete=django.db.models.deletion.PROTECT, related_name='licencias_funcionamiento', to='app_lf_itse.expediente')),
                ('licencia_principal', models.ForeignKey(blank=True, db_column='licencia_principal_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='licencias_dependientes', to='app_lf_itse.licenciafuncionamiento')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.PROTECT, related_name='licencias_funcionamiento_digitadas', to=settings.AUTH_USER_MODEL)),
                ('nivel_riesgo', models.ForeignKey(db_column='nivel_riesgo_id', on_delete=django.db.models.deletion.PROTECT, to='app_lf_itse.nivelriesgo')),
            ],
            options={
                'db_table': 'licencias_funcionamiento',
            },
        ),
        migrations.CreateModel(
            name='LicenciaFuncionamientoArchivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('nombre_original', models.CharField(max_length=255)),
                ('nombre_archivo', models.CharField(max_length=255)),
                ('ruta_archivo', models.CharField(max_length=500)),
                ('extension', models.CharField(max_length=20)),
                ('tamanio_bytes', models.BigIntegerField()),
                ('fecha_digitacion', models.DateTimeField()),
                ('licencia_funcionamiento', models.ForeignKey(db_column='licencia_funcionamiento_id', on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='app_lf_itse.licenciafuncionamiento')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'licencias_funcionamiento_archivos',
            },
        ),
        migrations.CreateModel(
            name='LicenciaFuncionamientoEstado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_estado', models.DateField()),
                ('documento', models.CharField(max_length=100)),
                ('observaciones', models.CharField(max_length=1000)),
                ('fecha_digitacion', models.DateTimeField()),
                ('estado', models.ForeignKey(db_column='estado_id', on_delete=django.db.models.deletion.PROTECT, to='app_lf_itse.estado')),
                ('licencia_funcionamiento', models.ForeignKey(db_column='licencia_funcionamiento_id', on_delete=django.db.models.deletion.CASCADE, related_name='historial_estados', to='app_lf_itse.licenciafuncionamiento')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'licencias_funcionamiento_estados',
            },
        ),
        migrations.CreateModel(
            name='LicenciaFuncionamientoGiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_digitacion', models.DateTimeField()),
                ('giro', models.ForeignKey(db_column='giro_id', on_delete=django.db.models.deletion.PROTECT, to='app_lf_itse.giro')),
                ('licencia_funcionamiento', models.ForeignKey(db_column='licencia_funcionamiento_id', on_delete=django.db.models.deletion.CASCADE, related_name='giros', to='app_lf_itse.licenciafuncionamiento')),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'licencias_funcionamiento_giros',
            },
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_persona', models.CharField(choices=[('N', 'Natural'), ('J', 'Jurídica')], max_length=1)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('X', 'Prefiero no decirlo')], default='X', max_length=1)),
                ('apellido_paterno', models.CharField(blank=True, max_length=50, null=True)),
                ('apellido_materno', models.CharField(blank=True, max_length=50, null=True)),
                ('nombres', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=250)),
                ('distrito', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('departamento', models.CharField(max_length=100)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('correo_electronico', models.CharField(blank=True, max_length=150, null=True)),
                ('fecha_creacion', models.DateTimeField()),
                ('fecha_actualizacion', models.DateTimeField()),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'personas',
            },
        ),
        migrations.AddField(
            model_name='licenciafuncionamiento',
            name='conductor',
            field=models.ForeignKey(db_column='conductor_id', on_delete=django.db.models.deletion.PROTECT, related_name='licencias_funcionamiento_conductor', to='app_lf_itse.persona'),
        ),
        migrations.AddField(
            model_name='licenciafuncionamiento',
            name='titular',
            field=models.ForeignKey(db_column='titular_id', on_delete=django.db.models.deletion.PROTECT, related_name='licencias_funcionamiento_titular', to='app_lf_itse.persona'),
        ),
        migrations.AddField(
            model_name='itse',
            name='conductor',
            field=models.ForeignKey(db_column='conductor_id', on_delete=django.db.models.deletion.PROTECT, related_name='itse_conductor', to='app_lf_itse.persona'),
        ),
        migrations.AddField(
            model_name='itse',
            name='titular',
            field=models.ForeignKey(db_column='titular_id', on_delete=django.db.models.deletion.PROTECT, related_name='itse_titular', to='app_lf_itse.persona'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='representante',
            field=models.ForeignKey(blank=True, db_column='representante_id', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expedientes_como_representante', to='app_lf_itse.persona'),
        ),
        migrations.AddField(
            model_name='expediente',
            name='solicitante',
            field=models.ForeignKey(db_column='solicitante_id', on_delete=django.db.models.deletion.PROTECT, related_name='expedientes_como_solicitante', to='app_lf_itse.persona'),
        ),
        migrations.CreateModel(
            name='PersonaDocumento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento', models.CharField(max_length=20)),
                ('persona', models.ForeignKey(db_column='persona_id', on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='app_lf_itse.persona')),
                ('tipo_documento_identidad', models.ForeignKey(db_column='tipo_documento_identidad_id', on_delete=django.db.models.deletion.PROTECT, to='app_lf_itse.tipodocumentoidentidad')),
            ],
            options={
                'db_table': 'personas_documentos',
            },
        ),
        migrations.AddField(
            model_name='licenciafuncionamiento',
            name='tipo_letrero',
            field=models.ForeignKey(db_column='tipo_letrero_id', on_delete=django.db.models.deletion.PROTECT, to='app_lf_itse.tipoletrero'),
        ),
        migrations.AddField(
            model_name='licenciafuncionamiento',
            name='tipo_licencia',
            field=models.ForeignKey(db_column='tipo_licencia_id', on_delete=django.db.models.deletion.PROTECT, to='app_lf_itse.tipolicencia'),
        ),
        migrations.CreateModel(
            name='TipoProcedimientoTupa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=250)),
                ('monto', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('plazo_atencion_dias', models.PositiveIntegerField(default=0)),
                ('dias_alerta_vencimiento', models.PositiveIntegerField(default=0)),
                ('esta_activo', models.BooleanField(default=True)),
                ('requiere_lf', models.BooleanField(default=True)),
                ('requiere_itse', models.BooleanField(default=True)),
                ('fecha_digitacion', models.DateTimeField(default=django.utils.timezone.now)),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('unidad_organica', models.ForeignKey(db_column='unidad_organica_id', on_delete=django.db.models.deletion.PROTECT, to='app_lf_itse.unidadorganica')),
            ],
            options={
                'db_table': 'tipos_procedimiento_tupa',
            },
        ),
        migrations.AddField(
            model_name='expediente',
            name='tipo_procedimiento_tupa',
            field=models.ForeignKey(db_column='tipo_procedimiento_tupa_id', on_delete=django.db.models.deletion.PROTECT, to='app_lf_itse.tipoprocedimientotupa'),
        ),
        migrations.CreateModel(
            name='UsuarioPerfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expedientes', models.BooleanField(default=False)),
                ('licencias', models.BooleanField(default=False)),
                ('itse', models.BooleanField(default=False)),
                ('admin', models.BooleanField(default=False)),
                ('fecha_digitacion', models.DateTimeField()),
                ('user', models.OneToOneField(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='perfil_lf_itse', to=settings.AUTH_USER_MODEL)),
                ('user_digitador', models.ForeignKey(db_column='user_id_digitador', on_delete=django.db.models.deletion.PROTECT, related_name='perfiles_digitados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'usuarios_perfiles',
            },
        ),
        migrations.CreateModel(
            name='Zonificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('esta_activo', models.BooleanField(default=True)),
                ('fecha_digitacion', models.DateTimeField()),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'zonificaciones',
            },
        ),
        migrations.AddField(
            model_name='licenciafuncionamiento',
            name='zonificacion',
            field=models.ForeignKey(db_column='zonificacion_id', on_delete=django.db.models.deletion.PROTECT, to='app_lf_itse.zonificacion'),
        ),
        migrations.CreateModel(
            name='AutorizacionImprocedente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_autorizacion', models.CharField(max_length=4)),
                ('fecha_rechazo', models.DateField()),
                ('documento', models.CharField(max_length=100)),
                ('observaciones', models.CharField(max_length=1000)),
                ('fecha_digitacion', models.DateTimeField()),
                ('usuario', models.ForeignKey(db_column='usuario_id', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('expediente', models.ForeignKey(db_column='expediente_id', on_delete=django.db.models.deletion.CASCADE, related_name='autorizaciones_improcedentes', to='app_lf_itse.expediente')),
            ],
            options={
                'db_table': 'autorizaciones_improcedentes',
                'indexes': [models.Index(fields=['expediente', 'tipo_autorizacion'], name='ix_aut_impr_exp_tp')],
            },
        ),
        migrations.AddConstraint(
            model_name='giro',
            constraint=models.UniqueConstraint(condition=models.Q(('ciiu_id__isnull', False)), fields=('ciiu_id',), name='uq_giros_ciiu_id'),
        ),
        migrations.AddIndex(
            model_name='personadocumento',
            index=models.Index(fields=['tipo_documento_identidad', 'numero_documento'], name='ix_perdoc_tiponum'),
        ),
        migrations.AddConstraint(
            model_name='personadocumento',
            constraint=models.UniqueConstraint(fields=('persona', 'tipo_documento_identidad'), name='uq_perdoc_per_tip'),
        ),
    ]
