# Generated by Django 6.0.3 on 2026-05-01 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_lf_itse', '0002_inspector_itseinspector'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspector',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='inspector',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='itseinspector',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='itseinspector',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
